"""QQ 双通道抽象层：官方族（qq_official / qq_official_webhook）与 OneBot（aiocqhttp）。

通道对象对上层暴露与 QQGroupAPI 一致的方法名，便于 ActionExecutor / JoinReviewer /
ApprovalPolicyService 无感切换。
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

OFFICIAL_NAMES = {"qq_official", "qq_official_webhook"}
ONEBOT_NAMES = {"aiocqhttp"}


def channel_kind(name: str) -> str:
    """按适配器名返回通道类型：official / onebot / 空串。"""
    if name in OFFICIAL_NAMES:
        return "official"
    if name in ONEBOT_NAMES:
        return "onebot"
    return ""


@runtime_checkable
class Channel(Protocol):
    """通道协议（方法名与 QQGroupAPI 对齐）。"""

    kind: str
    platform_id: str

    @property
    def available(self) -> bool: ...

    def dry_run(self) -> bool: ...

    async def probe(self, group_id: str, *, caller: str = "probe") -> dict[str, Any]: ...
    async def get_group_info(self, group_id: str, *, caller: str = "probe") -> Any: ...
    async def get_bot_state(self, group_id: str, *, caller: str = "probe") -> Any: ...
    async def get_restrict_setting(self, group_id: str, *, caller: str = "probe") -> dict[str, Any]: ...
    async def mute_member(self, group_id: str, member_openid: str, *, seconds: int, caller: str = "moderation") -> dict[str, Any]: ...
    async def unmute_member(self, group_id: str, member_openid: str, *, caller: str = "moderation") -> dict[str, Any]: ...
    async def recall_message(self, group_id: str, message_id: str, *, caller: str = "moderation") -> dict[str, Any]: ...
    async def list_members(self, group_id: str, *, caller: str = "member_admin") -> dict[str, Any]: ...
    async def get_member(self, group_id: str, member_openid: str, *, caller: str = "member_admin") -> Any: ...
    async def batch_remove_members(self, group_id: str, member_openids: list, *, add_to_blacklist: bool = False, caller: str = "member_admin") -> dict[str, Any]: ...
    async def get_blacklist(self, group_id: str, *, limit: int = 20, caller: str = "member_admin") -> dict[str, Any]: ...
    async def update_blacklist(self, group_id: str, *, op: str, member_openids: list, caller: str = "member_admin") -> dict[str, Any]: ...
    async def join_request_list(self, group_id: str, *, cursor: str = "", limit: int = 20, caller: str = "join_review") -> dict[str, Any]: ...
    async def approve_join_request(self, group_id: str, member_openid: str, *, op: str, join_request_id: str = "", reject_reason: str = "", add_to_blacklist: bool = False, caller: str = "join_review") -> dict[str, Any]: ...
    async def get_applicant_profile(self, request: dict, *, caller: str = "join_review") -> dict[str, Any]: ...
